export const ACTIVITY_TAG = {
    HOME: 'HOME',
    COUNTER: 'COUNTER',
    LOGIN_ACTIVITY: 'LOGIN_ACTIVITY',
    MESSAGE: 'MESSAGE',
    REGISTER_ACTIVITY: 'REGISTER_ACTIVITY',
    FORGET: 'FORGET',
    CHANGE: 'CHANGE',
    POST: 'POST',
    NAV: 'NAV'
}